export const TYPES = {
  AuditService: Symbol.for('AuditService'),
  AuthService: Symbol.for('AuthService'),
  RbacRegistryService: Symbol.for('RbacRegistryService'),
  RbacService: Symbol.for('RbacService'),
  RbacRepository: Symbol.for('RbacRepository'),

  // RBAC Specialized Services
  RbacCoreService: Symbol.for('RbacCoreService'),
  RbacFeatureService: Symbol.for('RbacFeatureService'),
  RbacDelegationService: Symbol.for('RbacDelegationService'),
  RbacAuditService: Symbol.for('RbacAuditService'),
  RbacPublishingService: Symbol.for('RbacPublishingService'),
  RbacStatisticsService: Symbol.for('RbacStatisticsService'),

  // Licensing Services
  LicensingService: Symbol.for('LicensingService'),
  PermissionValidationService: Symbol.for('PermissionValidationService'),
  FeaturePermissionService: Symbol.for('FeaturePermissionService'),
  PermissionDeploymentService: Symbol.for('PermissionDeploymentService'),

  // Phase 5 Optimization & Monitoring Services
  MaterializedViewRefreshService: Symbol.for('MaterializedViewRefreshService'),
  LicenseMonitoringService: Symbol.for('LicenseMonitoringService'),
  LicenseValidationService: Symbol.for('LicenseValidationService'),
  MetricsService: Symbol.for('MetricsService'),

  // Encryption Services
  EncryptionService: Symbol.for('EncryptionService'),
  EncryptionKeyManager: Symbol.for('EncryptionKeyManager'),
  EncryptionStrategy: Symbol.for('EncryptionStrategy'),

  // User Role Service
  UserRoleService: Symbol.for('UserRoleService'),

  // Sidebar Service
  SidebarService: Symbol.for('SidebarService'),

  // Menu Services
  MenuAccessService: Symbol.for('MenuAccessService'),
  MenuRenderingService: Symbol.for('MenuRenderingService'),
  MenuManagementService: Symbol.for('MenuManagementService'),

  // RBAC Adapters
  IRoleAdapter: Symbol.for('IRoleAdapter'),
  IPermissionAdapter: Symbol.for('IPermissionAdapter'),
  IRolePermissionAdapter: Symbol.for('IRolePermissionAdapter'),
  IUserRoleManagementAdapter: Symbol.for('IUserRoleManagementAdapter'),
  IFeatureCatalogAdapter: Symbol.for('IFeatureCatalogAdapter'),
  ITenantFeatureGrantAdapter: Symbol.for('ITenantFeatureGrantAdapter'),
  IDelegationAdapter: Symbol.for('IDelegationAdapter'),
  IRbacAuditAdapter: Symbol.for('IRbacAuditAdapter'),
  IPublishingAdapter: Symbol.for('IPublishingAdapter'),

  // Licensing Adapters
  IProductOfferingAdapter: Symbol.for('IProductOfferingAdapter'),
  ILicenseFeatureBundleAdapter: Symbol.for('ILicenseFeatureBundleAdapter'),
  ILicenseAssignmentAdapter: Symbol.for('ILicenseAssignmentAdapter'),
  IFeaturePermissionAdapter: Symbol.for('IFeaturePermissionAdapter'),
  IPermissionRoleTemplateAdapter: Symbol.for('IPermissionRoleTemplateAdapter'),

  // RBAC Repositories
  IRoleRepository: Symbol.for('IRoleRepository'),
  IPermissionRepository: Symbol.for('IPermissionRepository'),
  IUserRoleManagementRepository: Symbol.for('IUserRoleManagementRepository'),
  IRolePermissionRepository: Symbol.for('IRolePermissionRepository'),
  IFeatureCatalogRepository: Symbol.for('IFeatureCatalogRepository'),
  ITenantFeatureGrantRepository: Symbol.for('ITenantFeatureGrantRepository'),
  IDelegationRepository: Symbol.for('IDelegationRepository'),
  IRbacAuditRepository: Symbol.for('IRbacAuditRepository'),
  IPublishingRepository: Symbol.for('IPublishingRepository'),

  // Licensing Repositories
  IProductOfferingRepository: Symbol.for('IProductOfferingRepository'),
  ILicenseFeatureBundleRepository: Symbol.for('ILicenseFeatureBundleRepository'),
  ILicenseAssignmentRepository: Symbol.for('ILicenseAssignmentRepository'),
  IFeaturePermissionRepository: Symbol.for('IFeaturePermissionRepository'),
  IPermissionRoleTemplateRepository: Symbol.for('IPermissionRoleTemplateRepository'),

  ChartOfAccountService: Symbol.for('ChartOfAccountService'),
  IAccountAdapter: Symbol.for('IAccountAdapter'),
  IAccountRepository: Symbol.for('IAccountRepository'),
  IAnnouncementAdapter: Symbol.for('IAnnouncementAdapter'),
  IActivityLogAdapter: Symbol.for('IActivityLogAdapter'),
  IActivityLogRepository: Symbol.for('IActivityLogRepository'),
  IAnnouncementRepository: Symbol.for('IAnnouncementRepository'),
  IAuthAdapter: Symbol.for('IAuthAdapter'),
  IAuthUserAdapter: Symbol.for('IAuthUserAdapter'),
  IAuthRepository: Symbol.for('IAuthRepository'),
  IBudgetAdapter: Symbol.for('IBudgetAdapter'),
  IBudgetRepository: Symbol.for('IBudgetRepository'),
  ICategoryAdapter: Symbol.for('ICategoryAdapter'),
  ICategoryRepository: Symbol.for('ICategoryRepository'),
  IChartOfAccountAdapter: Symbol.for('IChartOfAccountAdapter'),
  IChartOfAccountRepository: Symbol.for('IChartOfAccountRepository'),
  IErrorLogAdapter: Symbol.for('IErrorLogAdapter'),
  IErrorLogRepository: Symbol.for('IErrorLogRepository'),
  IFamilyRelationshipAdapter: Symbol.for('IFamilyRelationshipAdapter'),
  IFamilyRelationshipRepository: Symbol.for('IFamilyRelationshipRepository'),
  IFinanceDashboardAdapter: Symbol.for('IFinanceDashboardAdapter'),
  IFinanceDashboardRepository: Symbol.for('IFinanceDashboardRepository'),
  IFinancialSourceAdapter: Symbol.for('IFinancialSourceAdapter'),
  IFinancialSourceRepository: Symbol.for('IFinancialSourceRepository'),
  IFinancialTransactionAdapter: Symbol.for('IFinancialTransactionAdapter'),
  IFinancialTransactionHeaderRepository: Symbol.for('IFinancialTransactionHeaderRepository'),
  IFinancialTransactionHeaderAdapter: Symbol.for('IFinancialTransactionHeaderAdapter'),
  IFinancialTransactionRepository: Symbol.for('IFinancialTransactionRepository'),
  IFiscalPeriodAdapter: Symbol.for('IFiscalPeriodAdapter'),
  IFiscalYearAdapter: Symbol.for('IFiscalYearAdapter'),
  IFiscalYearRepository: Symbol.for('IFiscalYearRepository'),
  IFundBalanceAdapter: Symbol.for('IFundBalanceAdapter'),
  IFundBalanceRepository: Symbol.for('IFundBalanceRepository'),
  IFundAdapter: Symbol.for('IFundAdapter'),
  IFundRepository: Symbol.for('IFundRepository'),
  IIncomeDashboardAdapter: Symbol.for('IIncomeDashboardAdapter'),
  IIncomeDashboardRepository: Symbol.for('IIncomeDashboardRepository'),
  IIncomeExpenseTransactionAdapter: Symbol.for('IIncomeExpenseTransactionAdapter'),
  IIncomeExpenseTransactionMappingRepository: Symbol.for('IIncomeExpenseTransactionMappingRepository'),
  IIncomeExpenseTransactionMappingAdapter: Symbol.for('IIncomeExpenseTransactionMappingAdapter'),
  IIncomeExpenseTransactionRepository: Symbol.for('IIncomeExpenseTransactionRepository'),
  ILicenseAdapter: Symbol.for('ILicenseAdapter'),
  ILicenseFeatureAdapter: Symbol.for('ILicenseFeatureAdapter'),
  ILicenseFeatureRepository: Symbol.for('ILicenseFeatureRepository'),
  ILicensePlanAdapter: Symbol.for('ILicensePlanAdapter'),
  ILicensePlanRepository: Symbol.for('ILicensePlanRepository'),
  ILicenseRepository: Symbol.for('ILicenseRepository'),
  IMemberAdapter: Symbol.for('IMemberAdapter'),
  IMemberRepository: Symbol.for('IMemberRepository'),
  IMembersDashboardAdapter: Symbol.for('IMembersDashboardAdapter'),
  IMembersDashboardRepository: Symbol.for('IMembersDashboardRepository'),
  IMembershipStageAdapter: Symbol.for('IMembershipStageAdapter'),
  IMembershipStageRepository: Symbol.for('IMembershipStageRepository'),
  IMembershipCenterAdapter: Symbol.for('IMembershipCenterAdapter'),
  IMembershipCenterRepository: Symbol.for('IMembershipCenterRepository'),
  IMembershipStageHistoryAdapter: Symbol.for('IMembershipStageHistoryAdapter'),
  IMembershipStageHistoryRepository: Symbol.for('IMembershipStageHistoryRepository'),
  IMemberCarePlanAdapter: Symbol.for('IMemberCarePlanAdapter'),
  IMemberCarePlanRepository: Symbol.for('IMemberCarePlanRepository'),
  IMemberServingAssignmentAdapter: Symbol.for('IMemberServingAssignmentAdapter'),
  IMemberServingAssignmentRepository: Symbol.for('IMemberServingAssignmentRepository'),
  IMemberDiscipleshipPlanAdapter: Symbol.for('IMemberDiscipleshipPlanAdapter'),
  IMemberDiscipleshipPlanRepository: Symbol.for('IMemberDiscipleshipPlanRepository'),
  IMemberDiscipleshipMilestoneAdapter: Symbol.for('IMemberDiscipleshipMilestoneAdapter'),
  IMemberDiscipleshipMilestoneRepository: Symbol.for('IMemberDiscipleshipMilestoneRepository'),
  IMemberGivingProfileAdapter: Symbol.for('IMemberGivingProfileAdapter'),
  IMemberGivingProfileRepository: Symbol.for('IMemberGivingProfileRepository'),
  IMemberProfileAdapter: Symbol.for('IMemberProfileAdapter'),
  IMemberProfileRepository: Symbol.for('IMemberProfileRepository'),
  IMemberTagAdapter: Symbol.for('IMemberTagAdapter'),
  IMemberTagRepository: Symbol.for('IMemberTagRepository'),
  IMemberTimelineEventAdapter: Symbol.for('IMemberTimelineEventAdapter'),
  IMemberTimelineEventRepository: Symbol.for('IMemberTimelineEventRepository'),
  IMembershipTypeAdapter: Symbol.for('IMembershipTypeAdapter'),
  IMembershipTypeRepository: Symbol.for('IMembershipTypeRepository'),
  IMenuItemAdapter: Symbol.for('IMenuItemAdapter'),
  IMenuItemRepository: Symbol.for('IMenuItemRepository'),
  IMenuPermissionAdapter: Symbol.for('IMenuPermissionAdapter'),
  IMenuPermissionRepository: Symbol.for('IMenuPermissionRepository'),
  IMessageAdapter: Symbol.for('IMessageAdapter'),
  IMessageThreadAdapter: Symbol.for('IMessageThreadAdapter'),
  INotificationAdapter: Symbol.for('INotificationAdapter'),
  IOfferingBatchAdapter: Symbol.for('IOfferingBatchAdapter'),
  IOpeningBalanceRepository: Symbol.for('IOpeningBalanceRepository'),
  IOpeningBalanceAdapter: Symbol.for('IOpeningBalanceAdapter'),
  IRelationshipTypeAdapter: Symbol.for('IRelationshipTypeAdapter'),
  IRelationshipTypeRepository: Symbol.for('IRelationshipTypeRepository'),
  IRoleMenuItemAdapter: Symbol.for('IRoleMenuItemAdapter'),
  IRoleMenuItemRepository: Symbol.for('IRoleMenuItemRepository'),
  ISettingAdapter: Symbol.for('ISettingAdapter'),
  ISettingRepository: Symbol.for('ISettingRepository'),
  ISourceRecentTransactionAdapter: Symbol.for('ISourceRecentTransactionAdapter'),
  ISubscriptionAdapter: Symbol.for('ISubscriptionAdapter'),
  ISubscriptionRepository: Symbol.for('ISubscriptionRepository'),
  ITenantAdapter: Symbol.for('ITenantAdapter'),
  ITenantRepository: Symbol.for('ITenantRepository'),
  IUiModuleRepository: Symbol.for('IUiModuleRepository'),
  IncomeExpenseTransactionService: Symbol.for('IncomeExpenseTransactionService'),
  LicenseFeatureService: Symbol.for('LicenseFeatureService'),
  MemberProfileService: Symbol.for('MemberProfileService'),
  RequestContext: Symbol.for('RequestContext'),
  TenantService: Symbol.for('TenantService'),
  UserMemberLinkService: Symbol.for('UserMemberLinkService'),
  UserMemberLinkRepository: Symbol.for('UserMemberLinkRepository'),
  MemberInvitationRepository: Symbol.for('MemberInvitationRepository'),
} as const;

export type TypeBindings = typeof TYPES;
export type TypeKey = keyof TypeBindings;
