import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{ts,tsx}", "./styles/**/*.{css,scss}"],
  darkMode: ["class", "[data-mode='dark']"],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--color-border))",
        input: "hsl(var(--color-input))",
        ring: "hsl(var(--color-ring))",
        background: "hsl(var(--color-background))",
        foreground: "hsl(var(--color-foreground))",
        primary: {
          DEFAULT: "hsl(var(--color-primary))",
          foreground: "hsl(var(--color-primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--color-secondary))",
          foreground: "hsl(var(--color-secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--color-destructive))",
          foreground: "hsl(var(--color-destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--color-muted))",
          foreground: "hsl(var(--color-muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--color-accent))",
          foreground: "hsl(var(--color-accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--color-popover))",
          foreground: "hsl(var(--color-popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--color-card))",
          foreground: "hsl(var(--color-card-foreground))",
        },
        tone: {
          light: {
            100: "var(--gray-light-100)",
            200: "var(--gray-light-200)",
            300: "var(--gray-light-300)",
            400: "var(--gray-light-400)",
            500: "var(--gray-light-500)",
            600: "var(--gray-light-600)",
            700: "var(--gray-light-700)",
            800: "var(--gray-light-800)",
            900: "var(--gray-light-900)",
          },
          dark: {
            100: "var(--gray-dark-100)",
            200: "var(--gray-dark-200)",
            300: "var(--gray-dark-300)",
            400: "var(--gray-dark-400)",
            500: "var(--gray-dark-500)",
            600: "var(--gray-dark-600)",
            700: "var(--gray-dark-700)",
            800: "var(--gray-dark-800)",
            900: "var(--gray-dark-900)",
          },
        },
        contextual: {
          light: {
            brand: {
              DEFAULT: "var(--context-light-brand-default)",
              active: "var(--context-light-brand-active)",
              light: "var(--context-light-brand-light)",
              clarity: "var(--context-light-brand-clarity)",
              inverse: "var(--context-light-brand-inverse)",
            },
            primary: {
              DEFAULT: "var(--context-light-primary-default)",
              active: "var(--context-light-primary-active)",
              light: "var(--context-light-primary-light)",
              clarity: "var(--context-light-primary-clarity)",
              inverse: "var(--context-light-primary-inverse)",
            },
            success: {
              DEFAULT: "var(--context-light-success-default)",
              active: "var(--context-light-success-active)",
              light: "var(--context-light-success-light)",
              clarity: "var(--context-light-success-clarity)",
              inverse: "var(--context-light-success-inverse)",
            },
            info: {
              DEFAULT: "var(--context-light-info-default)",
              active: "var(--context-light-info-active)",
              light: "var(--context-light-info-light)",
              clarity: "var(--context-light-info-clarity)",
              inverse: "var(--context-light-info-inverse)",
            },
            danger: {
              DEFAULT: "var(--context-light-danger-default)",
              active: "var(--context-light-danger-active)",
              light: "var(--context-light-danger-light)",
              clarity: "var(--context-light-danger-clarity)",
              inverse: "var(--context-light-danger-inverse)",
            },
            warning: {
              DEFAULT: "var(--context-light-warning-default)",
              active: "var(--context-light-warning-active)",
              light: "var(--context-light-warning-light)",
              clarity: "var(--context-light-warning-clarity)",
              inverse: "var(--context-light-warning-inverse)",
            },
            dark: {
              DEFAULT: "var(--context-light-dark-default)",
              active: "var(--context-light-dark-active)",
              light: "var(--context-light-dark-light)",
              clarity: "var(--context-light-dark-clarity)",
              inverse: "var(--context-light-dark-inverse)",
            },
            light: {
              DEFAULT: "var(--context-light-light-default)",
              active: "var(--context-light-light-active)",
              light: "var(--context-light-light-light)",
              clarity: "var(--context-light-light-clarity)",
              inverse: "var(--context-light-light-inverse)",
            },
            secondary: {
              DEFAULT: "var(--context-light-secondary-default)",
              active: "var(--context-light-secondary-active)",
              light: "var(--context-light-secondary-light)",
              clarity: "var(--context-light-secondary-clarity)",
              inverse: "var(--context-light-secondary-inverse)",
            },
          },
          dark: {
            brand: {
              DEFAULT: "var(--context-dark-brand-default)",
              active: "var(--context-dark-brand-active)",
              light: "var(--context-dark-brand-light)",
              clarity: "var(--context-dark-brand-clarity)",
              inverse: "var(--context-dark-brand-inverse)",
            },
            primary: {
              DEFAULT: "var(--context-dark-primary-default)",
              active: "var(--context-dark-primary-active)",
              light: "var(--context-dark-primary-light)",
              clarity: "var(--context-dark-primary-clarity)",
              inverse: "var(--context-dark-primary-inverse)",
            },
            success: {
              DEFAULT: "var(--context-dark-success-default)",
              active: "var(--context-dark-success-active)",
              light: "var(--context-dark-success-light)",
              clarity: "var(--context-dark-success-clarity)",
              inverse: "var(--context-dark-success-inverse)",
            },
            info: {
              DEFAULT: "var(--context-dark-info-default)",
              active: "var(--context-dark-info-active)",
              light: "var(--context-dark-info-light)",
              clarity: "var(--context-dark-info-clarity)",
              inverse: "var(--context-dark-info-inverse)",
            },
            danger: {
              DEFAULT: "var(--context-dark-danger-default)",
              active: "var(--context-dark-danger-active)",
              light: "var(--context-dark-danger-light)",
              clarity: "var(--context-dark-danger-clarity)",
              inverse: "var(--context-dark-danger-inverse)",
            },
            warning: {
              DEFAULT: "var(--context-dark-warning-default)",
              active: "var(--context-dark-warning-active)",
              light: "var(--context-dark-warning-light)",
              clarity: "var(--context-dark-warning-clarity)",
              inverse: "var(--context-dark-warning-inverse)",
            },
            dark: {
              DEFAULT: "var(--context-dark-dark-default)",
              active: "var(--context-dark-dark-active)",
              light: "var(--context-dark-dark-light)",
              clarity: "var(--context-dark-dark-clarity)",
              inverse: "var(--context-dark-dark-inverse)",
            },
            light: {
              DEFAULT: "var(--context-dark-light-default)",
              active: "var(--context-dark-light-active)",
              light: "var(--context-dark-light-light)",
              clarity: "var(--context-dark-light-clarity)",
              inverse: "var(--context-dark-light-inverse)",
            },
            secondary: {
              DEFAULT: "var(--context-dark-secondary-default)",
              active: "var(--context-dark-secondary-active)",
              light: "var(--context-dark-secondary-light)",
              clarity: "var(--context-dark-secondary-clarity)",
              inverse: "var(--context-dark-secondary-inverse)",
            },
          },
        },
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        DEFAULT: "var(--radius)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
      },
      fontFamily: {
        heading: "var(--font-family-heading)",
        body: "var(--font-family-body)",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        DEFAULT: "var(--shadow)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
        "2xl": "var(--shadow-2xl)",
      },
      spacing: {
        xs: "var(--spacing-xs)",
        sm: "var(--spacing-sm)",
        md: "var(--spacing-md)",
        lg: "var(--spacing-lg)",
        xl: "var(--spacing-xl)",
        "2xl": "var(--spacing-2xl)",
        "3xl": "var(--spacing-3xl)",
      },
    },
  },
  plugins: [],
};

export default config;
