/**
 * Tenant Deletion Report PDF Generator
 *
 * Generates a professional PDF report documenting bulk tenant deletion results,
 * including summary statistics, deleted tenant details, and any errors.
 */

import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

// ============================================================================
// Types
// ============================================================================

/** Tenant detail for the deletion report */
export interface DeletedTenantDetail {
  tenant_id: string;
  tenant_name: string;
  tenant_subdomain?: string;
  user_count: number;
  member_count: number;
  status: 'deleted' | 'failed';
  error?: string;
}

/** Data structure for the deletion report */
export interface TenantDeletionReportData {
  /** Deletion timestamp */
  deletionDate: Date;
  /** Overall deletion status */
  status: 'success' | 'partial' | 'failed';
  /** Summary counts */
  summary: {
    total_requested: number;
    total_deleted: number;
    total_failed: number;
    auth_users_deleted: number;
  };
  /** Deleted tenant details */
  tenants: DeletedTenantDetail[];
  /** Error message if overall failure */
  error?: string;
}

// ============================================================================
// Helper Functions
// ============================================================================

function getStatusColor(status: string): [number, number, number] {
  switch (status) {
    case 'deleted':
      return [34, 197, 94]; // Green
    case 'failed':
      return [239, 68, 68]; // Red
    default:
      return [128, 128, 128]; // Gray
  }
}

function addPageHeader(doc: jsPDF, title: string, pageWidth: number) {
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(66, 66, 66);
  doc.text(title, pageWidth / 2, 15, { align: 'center' });
  doc.setTextColor(0, 0, 0);

  // Divider line
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(14, 20, pageWidth - 14, 20);
}

function addFooter(doc: jsPDF, pageHeight: number, pageWidth: number, margin: number) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);

    // Footer line
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.3);
    doc.line(margin, pageHeight - 15, pageWidth - margin, pageHeight - 15);

    // Footer text
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by StewardTrack', margin, pageHeight - 10);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, pageHeight - 10, { align: 'right' });
  }
}

// ============================================================================
// PDF Generation
// ============================================================================

/**
 * Generate a Tenant Deletion Report PDF and trigger download
 */
export function generateTenantDeletionReport(data: TenantDeletionReportData): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'letter',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;
  let yOffset = 20;

  // ============================================================================
  // Page 1: Summary Page
  // ============================================================================

  // Report Title
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Tenant Deletion Report', pageWidth / 2, yOffset, { align: 'center' });
  yOffset += 10;

  // Deletion Details
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');

  const deletionDateStr = data.deletionDate.toLocaleString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  });

  doc.text(`Deletion Date: ${deletionDateStr}`, pageWidth / 2, yOffset, { align: 'center' });
  yOffset += 8;

  // Status Badge
  const statusColors: Record<string, { bg: [number, number, number]; text: [number, number, number] }> = {
    success: { bg: [34, 197, 94], text: [255, 255, 255] },
    partial: { bg: [234, 179, 8], text: [0, 0, 0] },
    failed: { bg: [239, 68, 68], text: [255, 255, 255] },
  };

  const statusLabels: Record<string, string> = {
    success: 'COMPLETED',
    partial: 'PARTIAL SUCCESS',
    failed: 'FAILED',
  };

  const statusConfig = statusColors[data.status] || statusColors.failed;
  const statusLabel = statusLabels[data.status] || 'UNKNOWN';

  // Draw status badge
  const badgeWidth = 45;
  const badgeHeight = 7;
  const badgeX = (pageWidth - badgeWidth) / 2;

  doc.setFillColor(...statusConfig.bg);
  doc.roundedRect(badgeX, yOffset, badgeWidth, badgeHeight, 2, 2, 'F');

  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...statusConfig.text);
  doc.text(statusLabel, pageWidth / 2, yOffset + 5, { align: 'center' });
  doc.setTextColor(0, 0, 0);

  yOffset += 15;

  // Divider line
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.5);
  doc.line(margin, yOffset, pageWidth - margin, yOffset);
  yOffset += 10;

  // Summary Section
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Deletion Summary', margin, yOffset);
  yOffset += 8;

  // Summary Table
  const summaryHeaders = ['Metric', 'Count'];
  const summaryBody = [
    ['Tenants Requested', String(data.summary.total_requested)],
    ['Tenants Deleted', String(data.summary.total_deleted)],
    ['Tenants Failed', String(data.summary.total_failed)],
    ['Auth Users Removed', String(data.summary.auth_users_deleted)],
  ];

  autoTable(doc, {
    startY: yOffset,
    head: [summaryHeaders],
    body: summaryBody,
    styles: {
      fontSize: 10,
      cellPadding: 4,
    },
    headStyles: {
      fillColor: [66, 66, 66],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
    },
    bodyStyles: {
      textColor: [0, 0, 0],
    },
    columnStyles: {
      0: { halign: 'left', fontStyle: 'bold', cellWidth: 80 },
      1: { halign: 'center', cellWidth: 40 },
    },
    didParseCell: (hookData) => {
      // Highlight deleted count in green
      if (hookData.row.index === 1 && hookData.column.index === 1 && hookData.section === 'body') {
        hookData.cell.styles.textColor = [34, 197, 94];
        hookData.cell.styles.fontStyle = 'bold';
      }
      // Highlight failed count in red (if any)
      if (hookData.row.index === 2 && hookData.column.index === 1 && hookData.section === 'body') {
        const failedCount = parseInt(hookData.cell.raw as string);
        if (failedCount > 0) {
          hookData.cell.styles.textColor = [239, 68, 68];
          hookData.cell.styles.fontStyle = 'bold';
        }
      }
    },
    margin: { left: margin, right: margin },
    tableWidth: 120,
  });

  yOffset = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 15;

  // Warning about permanent deletion
  doc.setFillColor(254, 243, 199); // Amber background
  doc.roundedRect(margin, yOffset, pageWidth - margin * 2, 20, 2, 2, 'F');

  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(180, 83, 9);
  doc.text('IMPORTANT', margin + 4, yOffset + 6);

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(146, 64, 14);
  const warningText = 'This deletion is permanent and cannot be undone. All tenant data, including members, donations, transactions, and user accounts (for users who only belonged to deleted tenants) have been permanently removed.';
  const splitWarning = doc.splitTextToSize(warningText, pageWidth - margin * 2 - 8);
  doc.text(splitWarning, margin + 4, yOffset + 11);

  doc.setTextColor(0, 0, 0);
  yOffset += 28;

  // ============================================================================
  // Deleted Tenants Detail Table
  // ============================================================================

  if (data.tenants.length > 0) {
    // Check if we need a new page
    if (yOffset > pageHeight - 60) {
      doc.addPage();
      addPageHeader(doc, 'Deleted Tenants Detail', pageWidth);
      yOffset = 25;
    } else {
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text('Deleted Tenants Detail', margin, yOffset);
      yOffset += 8;
    }

    const tenantsHeaders = ['Status', 'Tenant Name', 'Subdomain', 'Users', 'Members'];
    const tenantsBody = data.tenants.map(tenant => [
      tenant.status.toUpperCase(),
      tenant.tenant_name,
      tenant.tenant_subdomain || '-',
      String(tenant.user_count),
      String(tenant.member_count),
    ]);

    autoTable(doc, {
      startY: yOffset,
      head: [tenantsHeaders],
      body: tenantsBody,
      styles: {
        fontSize: 9,
        cellPadding: 3,
      },
      headStyles: {
        fillColor: [66, 66, 66],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
      },
      columnStyles: {
        0: { halign: 'center', cellWidth: 22 },
        1: { cellWidth: 55 },
        2: { cellWidth: 45 },
        3: { halign: 'center', cellWidth: 20 },
        4: { halign: 'center', cellWidth: 22 },
      },
      didParseCell: (hookData) => {
        if (hookData.section === 'body' && hookData.column.index === 0) {
          const status = hookData.cell.raw as string;
          const color = getStatusColor(status.toLowerCase());
          hookData.cell.styles.textColor = color;
          hookData.cell.styles.fontStyle = 'bold';
        }
      },
      margin: { left: margin, right: margin },
    });

    yOffset = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;
  }

  // ============================================================================
  // Errors Section (if any)
  // ============================================================================

  const failedTenants = data.tenants.filter(t => t.status === 'failed');

  if (failedTenants.length > 0) {
    // Check if we need a new page
    if (yOffset > pageHeight - 60) {
      doc.addPage();
      addPageHeader(doc, 'Deletion Errors', pageWidth);
      yOffset = 25;
    } else {
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(220, 38, 38);
      doc.text(`Errors (${failedTenants.length})`, margin, yOffset);
      doc.setTextColor(0, 0, 0);
      yOffset += 8;
    }

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');

    const maxWidth = pageWidth - margin * 2 - 10;

    failedTenants.forEach((tenant, index) => {
      if (yOffset > pageHeight - 30) {
        doc.addPage();
        yOffset = 20;
      }

      doc.setFont('helvetica', 'bold');
      const bulletText = `${index + 1}. ${tenant.tenant_name}`;
      doc.text(bulletText, margin, yOffset);
      yOffset += 4;

      if (tenant.error) {
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(100, 100, 100);
        const splitText = doc.splitTextToSize(tenant.error, maxWidth);

        splitText.forEach((line: string) => {
          if (yOffset > pageHeight - 20) {
            doc.addPage();
            yOffset = 20;
          }
          doc.text(line, margin + 5, yOffset);
          yOffset += 4;
        });

        doc.setTextColor(0, 0, 0);
      }

      yOffset += 4;
    });
  }

  // Global error message
  if (data.error) {
    if (yOffset > pageHeight - 40) {
      doc.addPage();
      yOffset = 20;
    }

    doc.setFillColor(254, 226, 226); // Red background
    doc.roundedRect(margin, yOffset, pageWidth - margin * 2, 15, 2, 2, 'F');

    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(185, 28, 28);
    doc.text('ERROR:', margin + 4, yOffset + 6);

    doc.setFont('helvetica', 'normal');
    const splitError = doc.splitTextToSize(data.error, pageWidth - margin * 2 - 30);
    doc.text(splitError, margin + 20, yOffset + 6);

    doc.setTextColor(0, 0, 0);
  }

  // ============================================================================
  // Footer on all pages
  // ============================================================================

  addFooter(doc, pageHeight, pageWidth, margin);

  // ============================================================================
  // Download
  // ============================================================================

  const timestamp = data.deletionDate.toISOString().slice(0, 19).replace(/[:-]/g, '').replace('T', '-');
  const filename = `tenant-deletion-report-${timestamp}.pdf`;
  doc.save(filename);
}
